name: CustomCraft
main: Joshet18\CustomCraft\Loader
description: "allows you to add recipes for Crafting Table, Furnace, Blast Furnace, Smoker Furnace"
version: 1.1
api: 5.0.0
author: Joshet18
src-namespace-prefix: Joshet18\CustomCraft
permissions:
  customcraft:
    default: op
    description: "permission to customcarft command"
  customcraft.reload:
    default: op
    description: "permission to execute reload command"
commands:
  customcraft:
    default: true
    permission: customcraft
    description: "customcraft commands"
